apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cinema-api-service
  annotations:
    # Đây là dòng lệnh quan trọng để Backstage hiển thị tab "Docs"
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cinema-movie-api
  description: OpenAPI contract for managing cinema movies.
  tags:
    - openapi
    - governance
spec:
  type: openapi
  lifecycle: experimental
  owner: guest
  definition:
    $text: ./swagger.json